### PR TITLE
Update keys and URL for beta release

### PR DESCRIPTION
**Pull request by emkll**
Use production endpoints, see https://github.com/freedomofpress/securedrop-workstation/pull/439 for test plan. 
#### Prior to merge
- [x] drop 1c7e11f (which will default to master for build)
#### Post merge
- [ ] Push a tag signature on the merge commit, with the release signing key

#### Test the build script
- The build script was transfered from securedrop-workstation, see https://github.com/freedomofpress/securedrop-workstation/pull/439
- Compare diff of this branch and test-build-script branch: https://github.com/freedomofpress/qubes-template-securedrop-workstation/compare/beta-release..test-build-script
- check out test-build-script branch
- make template
- [x] Template build is successful

#### Test the template build with prod prior to merge
- [x] https://github.com/freedomofpress/securedrop-debian-packages-lfs/pull/9 is merged, and changes deployed
-  Replace the SD signing key fingerprint with mine:
```
diff --git a/build-workstation-template b/build-workstation-template
index e280461..6f2fac9 100755
--- a/build-workstation-template
+++ b/build-workstation-template
@@ -36,8 +36,8 @@ make COMPONENTS="builder" get-sources
 # Add signing key to the keyring. The pubkey fingerprint tracked here is the "FPF Authority Key".
 # In order to test PRs, you may want to use a personal key with a temporary signed tag.
 # See comments above regarding feature branches in the git clone operation.
-gpg --homedir ${gpg_homedir} --keyserver pool.sks-keyservers.net --recv-key 22245C81E3BAEB4138B36061310F561200F4AD77 || exit 1;
-echo '22245C81E3BAEB4138B36061310F561200F4AD77:6:' | gpg --homedir ${gpg_homedir} --import-ownertrust;
+gpg --homedir ${gpg_homedir} --keyserver pool.sks-keyservers.net --recv-key AF775782949D263DAABB3387AAFB3575FAC82745 || exit 1;
+echo 'AF775782949D263DAABB3387AAFB3575FAC82745:6:' | gpg --homedir ${gpg_homedir} --import-ownertrust;
 
 # Get all sources
 make get-sources
```
- check out this branch (beta-release)
- make template
- [x] template build is successful

### CODE REVIEW

**Comment by conorsch** [comment]
Working on the `test-build-script` branch portion of review...

**Comment by conorsch** [comment]
Build script worked beautifully in a dispvm, building from the apt-test repos. Pulled RPM into dom0, installed, modified qvm-prefs, all working well.

**Comment by conorsch** [comment]
Proceeding with testing based on prod packages...

**Comment by conorsch** [comment]
Built a fresh template with prod packages, using a test-tag signed by @emkll. As before, template built without issue. Confirmed we're using the prod repos:

```
user@securedrop-workstation-buster:~$ uname -r
4.14.169-grsec-workstation
user@securedrop-workstation-buster:~$ grep -rFI freedom.press /etc/apt/
/etc/apt/sources.list.d/securedrop_workstation.list:deb https://apt.freedom.press buster main
```

Before merge, we'll have to drop the temporary commit, as you mentioned above. In addition, I believe we should update the README on the build steps, perhaps porting some of the docs in https://github.com/freedomofpress/securedrop-workstation/blob/6b415167c10c3ecf2dfba3e57e4b6496105a881b/README.md#building-the-templates Then we're ready for final review.

**Comment by emkll** [comment]
Thanks @conorsch , I've dropped the commit and updated the docs.

**Pull request merged**
